$(document).ready(function(){
    $("#signup-form").validate({
        rules:{
            fname:{
                required:true,
                minlength:4,
                maxlength:10,
            },
            lname:{
                required:true,
                minlength:4,
                maxlength:10,
            },
            email:{
                required:true,
                email:true
            },
            password:{
                required:true,
                maxlength:30,
                minlength:8,
            },
            confirmPassword:{
                required:true,
                maxlength:30,
                minlength:8,
                equalTo:"#password-form",
            },
            day:{
                required:true,
            },
            month:{
                required:true,
            },
            year:{
                required:true,
            },
            Gender:{
                required:true,
            },
        }
    })
})